### ISSUE TITLE
some problems occured while building the src

### ISSUE THREAD

**Issue by zhl2008** [prathprabhudesai/Panoramic-Image-Stitching-SIFT#1]
it looks like your libifs.a  was built on the platform of MAC OS, which could not work on the x64 linux.
I have spent some time to figure out the exact reason of the build error, and i notice your mac index files and the object files in your libifs.a  were " Mach-O 64-bit x86_64 object".

so, I suggest you can make some notice in  README.md, or just add the libifs.a for other architectures.

Thank you for your sharing :+1:

**Comment by zhl2008** [comment]
![qq 20170305182101](https://cloud.githubusercontent.com/assets/11239020/23589626/6613b33c-020b-11e7-98dc-b1737ed56060.png)

**Comment by prathprabhudesai** [comment]
Thank you. Yes they were built on MacOS. I shall add linux libraries too.
